export const TICK_RATE = 10; // sim ticks per second
export const TICKS_PER_DAY = 2400;
export const THINK_COOLDOWN_TICKS = 300;
export const MAX_PLAN_TASKS = 8;
export const LLM_TIMEOUT_MS = 90_000;
export const DAYS_PER_SEASON = 2;
export const SEASONS = ["spring", "summer", "autumn", "winter"] as const; // year = 8 days = ~32 real minutes
export const HUNGER_MAX = 100;
export const HUNGER_DECAY_PER_DAY = 50; // full → starving in 2 days without eating
export const HUNGER_EAT_THRESHOLD = 40; // engine interrupt below this
export const FOOD_PER_MEAL = 5;
export const HUNGER_PER_MEAL = 60;
export const FATIGUE_MAX = 100;
export const FATIGUE_DECAY_PER_DAY = 60;
export const FATIGUE_REST_THRESHOLD = 25;
export const FATIGUE_SLOWDOWN = 0.5; // work/move speed multiplier when fatigue < threshold
export const HEALTH_MAX = 100;
export const STARVATION_HEALTH_PER_DAY = 25; // ~4 days of grace at hunger 0
export const COLD_HEALTH_PER_DAY = 15; // winter with no wood to burn
export const WOOD_BURN_PER_AGENT_PER_DAY = 2; // winter only
export const BERRY_REGROWTH_PER_DAY = 4; // per food tile, spring/summer/autumn only, cap at initial amount
export const TREE_REGROWTH_PER_DAY = 1; // per depleted forest tile, cap 30
export const HOUSE_WOOD_COST = 15;
export const HOUSE_BUILD_TICKS = 400;
export const HOUSE_CAPACITY = 2;
export const IMMIGRATION_FOOD_DAYS_MIN = 4; // arrive on spring morning if stored food ≥ 4 days AND free housing
export const MAX_POPULATION = 10;
export const MAP_WIDTH = 64;
export const MAP_HEIGHT = 48;
export const AGENT_COUNT = 3;
export const AGENT_NAMES = ["Ash", "Birch", "Cedar"] as const;
export const MOVE_TICKS_PER_TILE = 3;
export const GATHER_TICKS = 20;
export const CARRY_CAPACITY = 5;
export const STOCKPILE_TARGET_WOOD = 30;
export const STOCKPILE_TARGET_FOOD = 20;
export const WANDER_RADIUS = 5;
export const WS_PORT = 8790;
export const TERRAIN_PATCH_SIZE = 4;
export const WATER_PATCH_CHANCE = 0.05;
export const ROCK_PATCH_CHANCE = 0.05;
export const FOREST_TILE_CHANCE = 0.25;
export const FOOD_TILE_CHANCE = 0.08;
export const WOOD_RESOURCE_MIN = 20;
export const WOOD_RESOURCE_MAX = 50;
export const FOOD_RESOURCE_MIN = 10;
export const FOOD_RESOURCE_MAX = 30;
